name: Run Year Progress Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */4 * *" # This runs at 00:00 every 4 days

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Or whatever Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow  # Add any other dependencies here

      - name: Run script
        run: python ./src/main.py # Adjust this to the path of your script
